stages:
  extract:
    cmd: python etl_main.py --stage extract
    deps:
      - src/churn_etl/pipeline/data_extraction_pipeline.py
      - src/churn_etl/components/data_extracting.py
      - etl_main.py
    outs:
      - ETL_artifacts/data_Extracting/extracted_data.csv

  transform:
    cmd: python etl_main.py --stage transform
    deps:
      - ETL_artifacts/data_Extracting/extracted_data.csv
      - src/churn_etl/pipeline/data_transformation_pipeline.py
      - src/churn_etl/components/data_transformation.py
      - etl_main.py
    outs:
      - ETL_artifacts/data_transformation/transformed_data.csv

  load:
    cmd: python etl_main.py --stage load
    deps:
      - ETL_artifacts/data_transformation/transformed_data.csv
      - src/churn_etl/pipeline/data_loading_pipeline.py
      - src/churn_etl/components/data_loader.py
      - etl_main.py
    outs:
      - Data/data.csv
