artifacts_root: ETL_artifacts

data_Extracting:
  root_dir: artifacts/data_Extracting
  csv_data: D:\repositories\coustomer churn prediction\old\E_Commerce_Dataset.csv
  postgresSQL:
    host: coustomer-database.cdwoe68s6i9h.us-east-1.rds.amazonaws.com
    port: 5432
    database: customer_churn_data
    table_name: customers
    user: postgres
    password: l2UfwUm1yUVusJVDEQVA 

data_transformation:
  root_dir: artifacts/data_transformation
  validation_schema: 
    CustomerID: int64
    Churn: int64
    Tenure: float64
    PreferredLoginDevice: object
    CityTier: int64
    WarehouseToHome: float64
    PreferredPaymentMode: object
    Gender: object
    HourSpendOnApp: float64
    NumberOfDeviceRegistered: int64
    PreferedOrderCat: object
    SatisfactionScore: int64
    MaritalStatus: object
    NumberOfAddress: int64
    Complain: int64
    OrderAmountHikeFromlastYear: float64
    CouponUsed: float64
    OrderCount: float64
    DaySinceLastOrder: float64
    CashbackAmount: float64

data_loading:
  root_dir: artifacts/data_loading
  etl_output: D:\repositories\coustomer churn prediction\src\churn_etl\data

