artifacts_root: prediction_artifacts

data_validation:
  root_dir: prediction_artifacts/data_validation
  validation_schema:
    CustomerID:
      dtype: int64
      constraints:
        min: 1
    Tenure:
      dtype: float64
      constraints:
        min: 0
    PreferredLoginDevice:
      dtype: object
      constraints:
        allowed_values: ["Mobile Phone", "Phone", "Computer"]
    CityTier:
      dtype: int64
      constraints:
        allowed_values: [1, 2, 3]
    WarehouseToHome:
      dtype: float64
      constraints:
        min: 3
    PreferredPaymentMode:
      dtype: object
    Gender:
      dtype: object
      constraints:
        allowed_values: ["Male", "Female"]
    HourSpendOnApp:
      dtype: float64
      constraints:
        min: 0
    NumberOfDeviceRegistered:
      dtype: float64
      constraints:
        min: 1
    PreferedOrderCat:
      dtype: object
    SatisfactionScore:
      dtype: int64
      constraints:
        min: 1
        max: 5
    MaritalStatus:
      dtype: object
      constraints:
        allowed_values: ["Single", "Married", "Divorced"]
    NumberOfAddress:
      dtype: int64
      constraints:
        min: 1
    Complain:
      dtype: int64
      constraints:
        allowed_values: [0, 1]
    OrderAmountHikeFromlastYear:
      dtype: float64
      constraints:
        min: 0
    CouponUsed:
      dtype: int64
      constraints:
        min: 0
    OrderCount:
      dtype: int64
      constraints:
        min: 0
    DaySinceLastOrder:
      dtype: int64
      constraints:
        min: 0
    CashbackAmount:
      dtype: float64
      constraints:
        min: 0
  validation_output: prediction_artifacts/data_validation/validation_report.txt

model_inference:
  columns:
  - Tenure
  - CityTier
  - WarehouseToHome
  - HourSpendOnApp
  - NumberOfDeviceRegistered
  - SatisfactionScore
  - NumberOfAddress
  - Complain
  - OrderAmountHikeFromlastYear
  - CouponUsed
  - OrderCount
  - DaySinceLastOrder
  - CashbackAmount
  - PreferredLoginDevice_Mobile Phone
  - PreferredLoginDevice_Phone
  - PreferredPaymentMode_COD
  - PreferredPaymentMode_Cash on Delivery
  - PreferredPaymentMode_Credit Card
  - PreferredPaymentMode_Debit Card
  - PreferredPaymentMode_E wallet
  - PreferredPaymentMode_UPI
  - Gender_Male
  - PreferedOrderCat_Grocery
  - PreferedOrderCat_Laptop & Accessory
  - PreferedOrderCat_Mobile
  - PreferedOrderCat_Mobile Phone
  - PreferedOrderCat_Others
  - MaritalStatus_Married
  - MaritalStatus_Single
